LIBDECORATION_H ifdefs
christianrauch/SDL pull request #1
Opened 2021-02-05 20:11 UTC by flibitijibibo

This makes it possible to build without libdecoration present on the system.

2021-02-05 23:17 UTC, christianrauch requested changes
Apart from the comments I left, I found that the commit "dynamic libdecoration loading" already works with the current upstream version of libdecoration without your forward-declaration patches.

Your changes in "use libdecoration header (with custom patch)" require the patches libdecoration, but it is not obvious what the benefit of this commit is.

2021-02-05 23:17 UTC, christianrauch commented on src/video/wayland/SDL_waylandwindow.c
> +        return SDL_SetError("FIXME libdecoration: Support GetWindowBordersSize");
I implemented this in https://gitlab.gnome.org/jadahl/libdecoration/-/merge_requests/44. But it turns out that this functionality is basically broken when `xdg-decoration` is used as it has no way to communicate the server-side decoration sizes to the client.

2021-02-05 23:17 UTC, christianrauch commented on src/video/wayland/SDL_waylandwindow.c
> +                                            window->max_h);
According to the documentation of [`SDL_SetWindowMaximumSize`](https://wiki.libsdl.org/SDL_SetWindowMaximumSize) this is the size of the client's area, but parameter `max_w` is `the maximum width of the window in pixels`.
So, which is it? "window" or "client"? The window area if different from the client area when window decorations are used. Right now, there is no way in libdecoration to enforce a specific min/max window size.

2021-02-05 23:17 UTC, christianrauch commented on CMakeLists.txt
> +dep_option(WAYLAND_LIBDECORATION "Use client-side window decorations on Wayland" ON "VIDEO_WAYLAND" ON)
I would like to keep `WAYLAND_DECORATION` as it's more generic. The name of the library (`libdecoration`) is [going to change to `libdecor`](https://gitlab.gnome.org/jadahl/libdecoration/-/merge_requests/31/diffs?commit_id=1a339954433a7511c0ff44a587e7d544eb811d5d) anyway to avoid name conflicts with a library of the same name originating from compiz.

2021-02-05 23:19 UTC, flibitijibibo commented on src/video/wayland/SDL_waylandwindow.c
> +        return SDL_SetError("FIXME libdecoration: Support GetWindowBordersSize");
Interesting - someone will have to figure that out from outside SDL then, and we'll use whatever the fix is.

2021-02-05 23:21 UTC, flibitijibibo commented on src/video/wayland/SDL_waylandwindow.c
> +                                            window->max_h);
It's client size. As far as SDL is concerned, we're always talking about the client, the border can do or be whatever it wants. We have handling inside our callbacks to ignore resizes past that cap, but I wasn't sure if this was necessary to communicate the same thing to libdecoration. If it's not necessary we can skip this commit entirely.

2021-02-05 23:22 UTC, flibitijibibo commented on CMakeLists.txt
> +dep_option(WAYLAND_LIBDECORATION "Use client-side window decorations on Wayland" ON "VIDEO_WAYLAND" ON)
Ah, then we'll need to change everything to `LIBDECOR` - we already have 3 backends so "generic" doesn't mean much at this point... "libdecor" as the backend name works for us.

2021-02-05 23:34 UTC, christianrauch commented on src/video/wayland/SDL_waylandwindow.c
> +                                            window->max_h);
Yes, you have to tell libdecoration about min/max toplevel sizes, as it will forward those directly via the xdg_toplevel functions (i.e. `xdg_toplevel_set_max_size` in this case).

I was just confused about the function name and parameter names. But if all is in terms of the client, then this is all fine.

2021-02-05 23:38 UTC, christianrauch commented on CMakeLists.txt
> +dep_option(WAYLAND_LIBDECORATION "Use client-side window decorations on Wayland" ON "VIDEO_WAYLAND" ON)
> we already have 3 backends so "generic" doesn't mean much at this point...

Well, there could be yet another way to provide client-side decorations :-)

I just think that `libdecor` is not a very widely used name. An option `WAYLAND_LIBDECOR` does not directly communicate what it is doing. So having an option named after the function is more sensible to me.

2021-02-05 23:44 UTC, flibitijibibo commented on CMakeLists.txt
> +dep_option(WAYLAND_LIBDECORATION "Use client-side window decorations on Wayland" ON "VIDEO_WAYLAND" ON)
Most of the options don't describe their context in detail... that's what the description is for. For WAYLAND_LIBDECOR we can write in "Use libdecor for client-side decoration support with Wayland".

If libdecor still feels nondescriptive, it sounds like the library has a name problem more than anything.

2021-02-05 23:52 UTC, christianrauch commented on CMakeLists.txt
> +dep_option(WAYLAND_LIBDECORATION "Use client-side window decorations on Wayland" ON "VIDEO_WAYLAND" ON)
> If libdecor still feels nondescriptive, it sounds like the library has a name problem more than anything.

If they weren't so popular, who would know that GIMP is a drawing program and Linux a kernel? :-)

2021-02-06 00:09 UTC, flibitijibibo commented on CMakeLists.txt
> +dep_option(WAYLAND_LIBDECORATION "Use client-side window decorations on Wayland" ON "VIDEO_WAYLAND" ON)
Tell you what, let's do it this way: I'm the one on the SDL maintenance side, and so WAYLAND_LIBDECOR in SDL is what I like, so that'll be what it is. As the libdecor maintainer you'll want to fix and add what SDL needs for us to incorporate it, so I would focus on those FIXMEs instead of what our variable names are.

2021-02-06 00:16 UTC, christianrauch commented on src/video/wayland/SDL_waylandwindow.c
> +        return SDL_SetError("FIXME libdecoration: Support GetWindowBordersSize");
This is maybe never going to happen: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/37

2021-02-06 00:22 UTC, flibitijibibo commented on src/video/wayland/SDL_waylandwindow.c
> +        return SDL_SetError("FIXME libdecoration: Support GetWindowBordersSize");
You may have to bring in the UE4 maintainers in this case - I think they have a channel on Freenode?

2021-02-06 00:26 UTC, flibitijibibo commented on src/video/wayland/SDL_waylandwindow.c
> +        return SDL_SetError("FIXME libdecoration: Support GetWindowBordersSize");
The GitHub megasearch comes up with some mixed cases... some are just weird about restoring window position while others are storing the data to match what they do with other backends https://github.com/search?q=SDL_GetWindowBordersSize&type=code

2021-02-06 11:20 UTC, christianrauch commented
@flibitijibibo Before I merge this, I would like to clarify why this PR has to be on top of "use libdecoration header (with custom patch)" (d8e4aaaa8887f5fbf06790a3b266f738829e523e).

The previous commit "dynamic libdecoration loading" (d53f938963dfea92ff98a3f247f10156e4d54b05) already provides the dynamic loading functionality, and d8e4aaa only replaces the forward definitions by the actual header. I would prefer to rebase this PR on the previous commit so that we do not have to patch libdocration in a way that every user has to include `wayland-client.h` as part of the interface manually.

2021-02-06 15:05 UTC, flibitijibibo commented
This can be applied however works best - it's all getting squashed at the end so the log isn't too important once the header issue is figured out.

2021-02-06 15:51 UTC, christianrauch commented
> This can be applied however works best - it's all getting squashed at the end so the log isn't too important once the header issue is figured out.

In this case, I just pushed that single "dynamic libdecoration loading" commit to the `decoration` branch and rebased your PR on top of it. Can you fix the remaining merge conflicts and push again? I will then just maintain this single branch for all decoration related functions that do not need a custom libdecoration patch.

2021-02-06 22:55 UTC, christianrauch commented
I rebased your commits into the `decoration` branch. There is no `decoration_dlopen` branch anymore.

2021-02-06 22:55 UTC, closed without merging